version: '3'

services:
  app:
    image: 'agwozdz/wsjar'
    build:
      context: .
    container_name: app
    depends_on:
      - db
      - flyway
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/diet
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8081:8080

  flyway:
    image: flyway/flyway:latest
    container_name: my-flyway
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=postgres
      - FLYWAY_URL=jdbc:postgresql://db:5432/diet
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ${PWD}/import:/flyway/sql
    depends_on:
      - db

  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=diet
    restart: always
    ports:
      - 5433:5432

